---
title: Git Demonstration
date: 11-26-2024
format:
    pdf:
        documentclass: article
        papersize: letter
        mainfont: Times New Roman
author:
    - name: 
        given: Gage
        family: Rowden
      id: GR
      orcid: 0000-0002-7517-0480
      email: rowde002@umn.edu
      affiliation:
          name: University of Minnesota
          city: Saint Paul
          state: MN
      corresponding: true

    - name: 
        given: Sarah
        family: Gresch
      id: SG
      orcid: 0000-0002-7517-0481
      email: rowde002@umn.edu
      affiliation:
          name: University of Minnesota
          city: Saint Paul
          state: MN
      corresponding: true

    - name: Albert Einstein
      orcid: 0000-0000-0000-0001
      email: email-not-invented@aol.com
      affiliation:
          name: Princeton University
          city: Newark
          state: NJ
abstract: Git can be difficult to learn, but is very rewarding in the end!
keywords: [git, github, Quarto]
bibliography:
    references.bib
bibliographystyle: 
    apa
---
<!-- # Git Demonstration

#### Authors
Gage Rowden<sup>1</sup>, Second Author<sup>2</sup>

#### Affiliations
<sup>1</sup>University of Minnesota\
<sup>2</sup>Colorado State University

## Abstract
Yada yada. -->




## Introduction
‘Who  made  the  flood?’  asked  Frodo. 

‘Elrond  commanded  it,’  answered  Gandalf.  ‘The  river  of this  valley  is  under  his  power,  and  it  will  rise  in  anger  when he  has  great  need  to  bar  the  Ford.  As  soon  as  the  captain  of the  Ringwraiths  rode  into  the  water  the  flood  was  released. If  I  may  say  so,  I  added  a  few  touches  of  my  own:  you  may not  have  noticed,  but  some  of  the  waves  took  the  form  of great  white  horses  with  shining  white  riders;  and  there  were many  rolling  and  grinding  boulders.  For  a  moment  I  was afraid  that  we  had  let  loose  too  fierce  a  wrath,  and  the  flood would  get  out  of  hand  and  wash  you  all  away.  There  is  great vigour  in  the  waters  that  come  down  from  the  snows  of  the Misty  Mountains.’ 

‘Yes,  it  all  comes  back  to  me  now,’  said  Frodo:  ‘the  tremendous  roaring.  I  thought  I  was  drowning,  with  my  friends  and enemies  and  all.  But  now  we  are  safe!’ 

Gandalf  looked  quickly  at  Frodo,  but  he  had  shut  his  eyes. ‘Yes,  you  are  all  safe  for  the  present.  Soon  there  will  be feasting  and  merrymaking  to  celebrate  the  victory  at  the  Ford of  Bruinen,  and  you  will  all  be  there  in  places  of  honour.’ 

‘Splendid!’  said  Frodo.  ‘It  is  wonderful  that  Elrond,  and Glorfindel  and  such  great  lords,  not  to  mention  Strider, should  take  so  much  trouble  and  show  me  so  much  kindness.’ 

‘Well,  there  are  many  reasons  why  they  should,’  said Gandalf,  smiling.  ‘I  am  one  good  reason.  The  Ring  is  another: you  are  the  Ring-bearer.  And  you  are  the  heir  of  Bilbo,  the Ring-finder.’ 

‘Dear  Bilbo!’  said  Frodo  sleepily.  ‘I  wonder  where  he  is.  I wish  he  was  here  and  could  hear  all  about  it.  It  would  have made  him  laugh.  The  cow  jumped  over  the  Moon!  And  the poor  old  troll!’  With  that  he  fell  fast  asleep.

## Materials & Methods

### RT-QuIC
RT-QuIC was performed like it should be according to @Schwabenlander2021.

### Statistical Analysis
We did the stats like we always have.\
We used MPR, described by @Rowden2023.

## Results

| **Sample** | **MPR** | **RAF** | **p-value** |  **Result**  |
|:----------:|:-------:|:-------:|:-----------:|:------------:|
|      1     |    12   |    .4   |     .001    |   Detected   |
|      2     |    2    |   .005  |     .12     |    Suspect   |
|      3     |   1.8   |    0    |     .999    | Not Detected |

```{r echo=FALSE, warning=FALSE, message=FALSE}
#| label: fig-cap-margin
#| fig-cap: "MPG vs horsepower, colored by transmission."
#| cap-location: bottom
library(tidyverse)
library(ggplot2)

mtcars %>%
  # mutate(cyl = factor(cyl)) %>%
  ggplot(aes(cyl, mpg, color = hp)) +
    geom_point() +
    geom_smooth(formula = y ~ x, method = "loess") +
    theme(legend.position = 'bottom')
```

## Discussion
We're not really sure what is going on here.


{{< pagebreak >}}

## References
::: {#refs}
:::